---
title: "annotation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Assignment using gene sets

```{r}
donors.integrated=readRDS("seurat-integrated-8.rds")

```



```{r}
#markers.mam <- findMarkers(donors.integrated, sce.mam$cluster, direction="up", lfc=1)

#find positive markers for all clusters
markers <- FindAllMarkers(donors.integrated, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 1)

c1=markers[markers$cluster==1 & markers$p_val_adj<=.05]

```

You may need to map symbols from to entrez id for goana

```{r mapping symbols to entrez for goana}
require(org.Hs.eg.db)
#keytypes(org.Hs.eg.db) #prints fields available for matching

#keys: enter list of genes in the format specified in "keytype"
#column: returned column field
entrez=mapIds(org.Hs.eg.db,keys= markers$gene, keytype="SYMBOL", column=("ENTREZID"))
markers$entrez=entrez


# number of cells in each cluster
ordered_clust=markers %>% group_by(cluster) %>% count %>% arrange(desc(n))



```

```{r goana on 5 largest cell pops}
#map symbols to entrez id for goana using DBi annotations
require(limma)
require(GO.db)

go_ls=list()

for (i in 1:dim(ordered_clust[1])){

#markers$ez=ent_symb$entrez
c_markers=markers[(markers$cluster==ordered_clust$cluster[i]) & (markers$p_val_adj<=.05), ]

go.out <- goana(unique(c_markers$ez[!is.na(c_markers$ez)]), species="Hs",  universe=NULL)

go.out <- go.out[order(go.out$P.DE),]
#N: number of genes in gene set
go.useful <- go.out[go.out$Ont=="BP" & go.out$N <= 200,]

#names the list with the cluster number
go_ls[[ordered_clust$cluster[i]]]=go.useful

print(paste("GO on cluster:", ordered_clust$cluster[i]))
}

```

clusters 4,6,7,10,12
```{r examine gene sets in each cluster}
head(go_ls[[4]])

```




files downloaded from CellMarker database
```{r loading cellmarker db markers}
human_markers=read.table("Human_cell_markers.txt", sep='\t',header = TRUE, stringsAsFactors = F)

single_markers=read.table("Single_cell_markers.txt", sep='\t',header = TRUE, stringsAsFactors = F)


markers=read.table("cluster_markers.txt")
```



```{r checking for occurrence of db markers in biomarker genes}

#matching based on human cell markers
hmatch=merge(markers, human_markers[,c("tissueType","cellName","geneSymbol")],by.x="gene",by.y="geneSymbol") 

#matching based on single cell markers


```

```{r checking for sc CM in biomarker genes}
biomarkers= markers[,c("cluster","gene")] #keep just the clusterid and genenames

bio_list=ls()

for (cluster in unique(biomarkers$cluster)){
  #print(cluster)
  
  #generate list of genes associated with each cluster
  cluster_gene_list= biomarkers[biomarkers$cluster==cluster, "gene"]
  
bio_list[toString(cluster)]= list(cluster_gene_list)

  
}
bio_list=lapply(bio_list,unlist)

#for each row there is a list of markers, which we will unpack here as ref_list
ref_list=strsplit(single_markers$geneSymbol,split = ", ")

lapply(bio_list, function(x) temp %in% x ) 


id=data.frame()
for (row in 1:nrow(biomarkers)){
  mark=biomarkers$gene[row]
  cluster=biomarkers$cluster[row]
  
  rowid= which(unlist(lapply(ref_short, function(x) mark %in% x)))
  if(length(rowid)) #if there are matching rows
     {
    
    print('included')
    
    #return cellname, tissuetype, marker
    newrow=c("name"=mark,"cluster"=cluster,single_markers[rowid,c("cellName","tissueType")])
    
    id=rbind(id, data.frame(newrow))
  }
}


  
 

```


```{r}
panglao=read.csv("panglao_output_top1gene.tsv",sep="\t")
```















## Alternative to CellMarker database
Use this package to access Cellmarker and Panglao db

https://cran.r-project.org/web/packages/scMappR/scMappR.pdf
```{r scmappr}
#GSVA dependency may need to be installed separately
require(scMappR)


internal <- tissue_scMappR_custom(genes,Signature,output_directory = "scMappR_Test_custom", toSave = TRUE)
```

